# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coursework.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='coursework.proto',
  package='',
  syntax='proto3',
  serialized_options=b'P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63oursework.proto\"C\n\x0bMatrices_in\x12\x19\n\x08Matrix_1\x18\x01 \x01(\x0b\x32\x07.Matrix\x12\x19\n\x08Matrix_2\x18\x02 \x01(\x0b\x32\x07.Matrix\"\'\n\nMatrix_out\x12\x19\n\x08Matrix_3\x18\x01 \x01(\x0b\x32\x07.Matrix\"*\n\x06Matrix\x12\x0c\n\x04rows\x18\x01 \x01(\x05\x12\x12\n\x06values\x18\x02 \x03(\x01\x42\x02\x10\x01\x32i\n\x0fMatrixOperation\x12\'\n\x08\x41\x64\x64ition\x12\x0c.Matrices_in\x1a\x0b.Matrix_out\"\x00\x12-\n\x0eMultiplication\x12\x0c.Matrices_in\x1a\x0b.Matrix_out\"\x00\x42\x02P\x01\x62\x06proto3'
)




_MATRICES_IN = _descriptor.Descriptor(
  name='Matrices_in',
  full_name='Matrices_in',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Matrix_1', full_name='Matrices_in.Matrix_1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Matrix_2', full_name='Matrices_in.Matrix_2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=87,
)


_MATRIX_OUT = _descriptor.Descriptor(
  name='Matrix_out',
  full_name='Matrix_out',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Matrix_3', full_name='Matrix_out.Matrix_3', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=128,
)


_MATRIX = _descriptor.Descriptor(
  name='Matrix',
  full_name='Matrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='Matrix.rows', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='Matrix.values', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=172,
)

_MATRICES_IN.fields_by_name['Matrix_1'].message_type = _MATRIX
_MATRICES_IN.fields_by_name['Matrix_2'].message_type = _MATRIX
_MATRIX_OUT.fields_by_name['Matrix_3'].message_type = _MATRIX
DESCRIPTOR.message_types_by_name['Matrices_in'] = _MATRICES_IN
DESCRIPTOR.message_types_by_name['Matrix_out'] = _MATRIX_OUT
DESCRIPTOR.message_types_by_name['Matrix'] = _MATRIX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Matrices_in = _reflection.GeneratedProtocolMessageType('Matrices_in', (_message.Message,), {
  'DESCRIPTOR' : _MATRICES_IN,
  '__module__' : 'coursework_pb2'
  # @@protoc_insertion_point(class_scope:Matrices_in)
  })
_sym_db.RegisterMessage(Matrices_in)

Matrix_out = _reflection.GeneratedProtocolMessageType('Matrix_out', (_message.Message,), {
  'DESCRIPTOR' : _MATRIX_OUT,
  '__module__' : 'coursework_pb2'
  # @@protoc_insertion_point(class_scope:Matrix_out)
  })
_sym_db.RegisterMessage(Matrix_out)

Matrix = _reflection.GeneratedProtocolMessageType('Matrix', (_message.Message,), {
  'DESCRIPTOR' : _MATRIX,
  '__module__' : 'coursework_pb2'
  # @@protoc_insertion_point(class_scope:Matrix)
  })
_sym_db.RegisterMessage(Matrix)


DESCRIPTOR._options = None
_MATRIX.fields_by_name['values']._options = None

_MATRIXOPERATION = _descriptor.ServiceDescriptor(
  name='MatrixOperation',
  full_name='MatrixOperation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=174,
  serialized_end=279,
  methods=[
  _descriptor.MethodDescriptor(
    name='Addition',
    full_name='MatrixOperation.Addition',
    index=0,
    containing_service=None,
    input_type=_MATRICES_IN,
    output_type=_MATRIX_OUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Multiplication',
    full_name='MatrixOperation.Multiplication',
    index=1,
    containing_service=None,
    input_type=_MATRICES_IN,
    output_type=_MATRIX_OUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATRIXOPERATION)

DESCRIPTOR.services_by_name['MatrixOperation'] = _MATRIXOPERATION

# @@protoc_insertion_point(module_scope)
